name: nopaws
description: An alternative app for University of South Alabama students

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons_maker: "^0.10.1"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/buses.json
    - assets/routes.json
    - assets/routesOriginal.json
    # temporary files please delete
    - assets/api.key
    - assets/transparency.png
    - assets/placeholder-map.png
    - assets/nopaws.png

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/nopaws.png"
